server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/share_it_repository?currentSchema=share_it
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        temp:
        use_jdbc_metadata_defaults: false
        hbm2ddl.auto: validate
    open-in-view: false #don't open transactions in view layer
  mvc:
    format:
      date: iso

logging:
  level:
    root: info
    jpa: info
    transactional: info